In [1]:
import os

import numpy as np
import torch
from lib.config import cfg

import lib.dataset.dataset3D as dataUtils
from lib.hybridnet.hybridnet import HybridNet
from lib.hybridnet.efficienttrack.efficienttrack import EfficientTrack
import lib.hybridnet.efficienttrack.darkpose as darkpose
from lib.config.project_manager import ProjectManager

project = ProjectManager()
project.load('Example_Project')

cfg = project.get_cfg()

Successfully loaded project Example_Project!


In [2]:
#Load datasets... currently still needed because they contain camera parameters etc

training_set = dataUtils.Dataset3D(cfg, set='train')
val_set = dataUtils.Dataset3D(cfg, set='val')

loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!


In [3]:
#Load HybridNet in inference mode

weightsHybridNet = '/home/timo/Documents/JARVIS-HybridNet/projects/Example_Project/models/HybridNet/Run_20211123-092606/HybridNet-d_10.pth'

hybridNet = HybridNet('inference', cfg, weightsHybridNet)

[Info] loaded weights: HybridNet-d_10.pth


In [4]:
#load center detection network in inference mode

weightsCenterDetect = 'pretrained/Monkey_Example/EfficientTrack_Center.pth'
centerDetect = EfficientTrack('CenterDetectInference', cfg, weightsCenterDetect)

In [5]:
#Predict poses for recording and create labeled videos

video_paths = [
    'Example_Recording/Camera_B.mp4',
    'Example_Recording/Camera_LBB.mp4',
    'Example_Recording/Camera_LBT.mp4',
    'Example_Recording/Camera_LC.mp4',
    'Example_Recording/Camera_LFB.mp4',
    'Example_Recording/Camera_LFT.mp4',
    'Example_Recording/Camera_RBB.mp4',
    'Example_Recording/Camera_RBT.mp4',
    'Example_Recording/Camera_RC.mp4',
    'Example_Recording/Camera_RFB.mp4',
    'Example_Recording/Camera_RFT.mp4',
    'Example_Recording/Camera_T.mp4', 
]

reproTool = val_set.reproTool
cameraMatrices = val_set.cameraMatrices
hybridNet.predictPosesVideos(centerDetect, reproTool, cameraMatrices,video_paths, 'PosePredictions', 
                             frameStart =15, frameEnd = 10000)

Analysing Frame  0
7
tensor([   2.6926, -117.4809,  600.5367], dtype=torch.float64)
7
tensor([   2.6843, -117.4601,  600.5233], dtype=torch.float64)
7
tensor([   2.6292, -117.4449,  600.5494], dtype=torch.float64)
8
tensor([   2.6630, -117.4873,  600.5588], dtype=torch.float64)
8
tensor([   2.6584, -117.4054,  600.7262], dtype=torch.float64)
8
tensor([   2.7379, -117.3752,  600.8019], dtype=torch.float64)
8
tensor([   2.7337, -117.3791,  600.7705], dtype=torch.float64)
8
tensor([   2.7154, -117.4401,  600.5653], dtype=torch.float64)
8
tensor([   2.6815, -117.4467,  600.5718], dtype=torch.float64)
8
tensor([   2.7273, -117.4668,  600.6185], dtype=torch.float64)
8
tensor([   2.8187, -117.4757,  600.6901], dtype=torch.float64)
8
tensor([   2.7787, -117.5547,  600.6810], dtype=torch.float64)
8
tensor([   2.7738, -117.5415,  600.7003], dtype=torch.float64)
8
tensor([   2.7672, -117.5732,  600.6386], dtype=torch.float64)
8
tensor([   2.8370, -117.5338,  600.5540], dtype=torch.float64)
8
tens

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.